### ISSUE TITLE
Oops, cannot start the server. @735im81no: Database 'default' needs migration!

### ISSUE THREAD

**Issue by derfWayne** [shafiquejamal/play-authentication#1]
@shafiquejamal  Attempting to start application with this command, activator clean compile start. 

Execution and compilation starts but hangs with the above/below error. I have all the databases created with tables that are in conf.db.migrations.default. 

Please find attach screen shots of database schema and conf file. Please advise why this exception is being thrown and what to do about it. Thanks

Below is full stack trace:

[debug] c.g.i.i.u.Stopwatch - Preloading singletons: 4525ms
Oops, cannot start the server.
@735im81no: Database 'default' needs migration!
	at org.flywaydb.play.PlayInitializer$$anonfun$org$flywaydb$play$PlayInitializer$$checkState$1.apply(PlayInitializer.scala:114)
	at org.flywaydb.play.PlayInitializer$$anonfun$org$flywaydb$play$PlayInitializer$$checkState$1.apply(PlayInitializer.scala:111)
	at scala.Option.foreach(Option.scala:257)
	at org.flywaydb.play.PlayInitializer.org$flywaydb$play$PlayInitializer$$checkState(PlayInitializer.scala:111)
	at org.flywaydb.play.PlayInitializer$$anonfun$onStart$1.apply(PlayInitializer.scala:129)
	at org.flywaydb.play.PlayInitializer$$anonfun$onStart$1.apply(PlayInitializer.scala:125)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:174)
	at org.flywaydb.play.PlayInitializer.onStart(PlayInitializer.scala:125)
	at org.flywaydb.play.PlayInitializer.<init>(PlayInitializer.scala:144)
	at org.flywaydb.play.PlayInitializer$$FastClassByGuice$$fd53e8fe.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:84)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:181)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:123)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:47)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:22)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)

<img width="283" alt="screen shot 2017-02-20 at 11 13 17 pm" src="https://cloud.githubusercontent.com/assets/11152179/23151672/7435365a-f7c2-11e6-8d02-a78f6450201b.png">
<img width="506" alt="screen shot 2017-02-20 at 11 13 57 pm" src="https://cloud.githubusercontent.com/assets/11152179/23151673/74396748-f7c2-11e6-87fd-c4202e696b16.png">
<img width="454" alt="screen shot 2017-02-20 at 11 13 24 pm" src="https://cloud.githubusercontent.com/assets/11152179/23151674/743a8f56-f7c2-11e6-8a33-d10e028bfa21.png">
<img width="449" alt="screen shot 2017-02-20 at 11 13 43 pm" src="https://cloud.githubusercontent.com/assets/11152179/23151675/743b7cea-f7c2-11e6-80ca-edb08a733be0.png">

**Comment by derfWayne** [comment]
@shafiquejamal

**Comment by shafiquejamal** [comment]
Hello, looks like you have to run the migration. 

Do not create any tables. Instead, create the database without any tables, and let the migration create the tables. 

Assuming you are running this on `localhost:9000`, open a browser and navigate to `localhost:9000/username/foo`. This should give you a prompt in the browser to run the migration. Click on the run migration link, then all should work fine.

Please let me know what happens. Thanks.

**Comment by derfWayne** [comment]
**## Running npm test yields this:**
FAILED TESTS:
  RequestResetPassword
    ✖ should exist
      Chrome 56.0.2924 (Mac OS X 10.12.2)
    Error: Expected undefined to exist
        at assert (eval at <anonymous> (/Users/fredurban/play-react-scalikejdbc-postgres-bootstrap4/reactapp/test/access/authentication/RequestResetPassword.test.jsx:2223:2), <anonymous>:29:9)
        at Expectation.toExist (eval at <anonymous> (/Users/fredurban/play-react-scalikejdbc-postgres-bootstrap4/reactapp/test/access/authentication/RequestResetPassword.test.jsx:2169:2), <anonymous>:52:28)
        at Context.eval (eval at <anonymous> (/Users/fredurban/play-react-scalikejdbc-postgres-bootstrap4/reactapp/test/access/authentication/RequestResetPassword.test.jsx:47:2), <anonymous>:14:49)

**## When running ;test;run in SBT console, these are the results:**
[info] DeferredAbortedSuite:
[info] Exception encountered when attempting to run a suite with class name: org.scalatest.DeferredAbortedSuite *** ABORTED ***
[info]   com.typesafe.config.ConfigException$UnresolvedSubstitution: application.conf @ file:/Users/fredurban/play-react-scalikejdbc-postgres-bootstrap4/target/scala-2.11/classes/application.conf: 393: Could not resolve substitution to a value: ${CRAUTH_JWT_VALIDITY_DAYS}
[info]   at com.typesafe.config.impl.ConfigReference.resolveSubstitutions(ConfigReference.java:108)
[info]   at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
[info]   at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
[info]   at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:379)
[info]   at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312)
[info]   at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:398)
[info]   at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
[info]   at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
[info]   at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:379)
[info]   at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312)
[info]   ...

**## Here are my environment variables in IntelliJ:**
<img width="1153" alt="screen shot 2017-02-21 at 7 29 48 pm" src="https://cloud.githubusercontent.com/assets/11152179/23193335/01e131b0-f86e-11e6-80a5-80b41b711bc8.png">

[info] *** 16 SUITES ABORTED ***
[error] Error: Total 32, Failed 0, Errors 16, Passed 16
[error] Error during tests:
[error] 	chat.ToServerAddContactMessageProcessorUTest
[error] 	access.registration.RegistrationControllerATest
[error] 	chat.ChatControllerATest
[error] 	access.registration.RegistrationFacadeATest
[error] 	access.authentication.AuthenticationControllerATest
[error] 	user.ScalikeJDBCUserDAOUTest
[error] 	chat.ToServerRequestMessagesMessageProcessorUTest
[error] 	chat.ChatMessageFacadeATest
[error] 	contact.ChatContactDAOUTest
[error] 	contact.ChatContactFacadeATest
[error] 	access.authentication.AuthenticationFacadeATest
[error] 	chat.BetterActorFlowUTest
[error] 	chat.ChatMessageDAOUTest
[error] 	user.UserControllerATest
[error] 	access.AuthenticatedActionUTest
[error] 	user.UserFacadeATest
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 111 s, completed Feb 21, 2017 7:24:13 PM

**## Hosting the application from SBT in IntelliJ allows me to stand it up, however navigating to the uri http://localhost:9000/username/foo throws the below exception in the SBT console. This is the original exception I got. I originally thought it was because of the environment variables. However, as you can see above, I have set all environment variables needed.**

[info] Compiling 102 Scala sources and 6 Java sources to /Users/fredurban/play-react-scalikejdbc-postgres-bootstrap4/target/scala-2.11/classes...
[error] p.c.s.n.PlayRequestHandler - Exception caught in Netty
[info] java.lang.NoClassDefFoundError: Could not initialize class play.api.http.DefaultHttpErrorHandler$
[info] 	at play.core.server.Server$class.logExceptionAndGetResult$1(Server.scala:45)
[info] 	at play.core.server.Server$class.getHandlerFor(Server.scala:65)
[info] 	at play.core.server.NettyServer.getHandlerFor(NettyServer.scala:47)
[info] 	at play.core.server.netty.PlayRequestHandler.handle(PlayRequestHandler.scala:82)
[info] 	at play.core.server.netty.PlayRequestHandler.channelRead(PlayRequestHandler.scala:163)
[info] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
[info] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
[info] 	at com.typesafe.netty.http.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:129)
[info] 	at com.typesafe.netty.http.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:96)
[info] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)

**Additionally I'm still unable to stand the app up with the command, activator clean compile start. I still get the same error above. Could be related however, I've yet to triage in that direction.**

**_Thanks for your help in this. Awaiting your response._**

**Comment by shafiquejamal** [comment]
Ok, I updated few things, please pull the changes note the following:

1. In application.conf, I changed `crauth.jwtValidityDays=${CRAUTH_JWT_VALIDITY_DAYS}` to `crauth.jwtValidityDays=${?CRAUTH_JWT_VALIDITY_DAYS}`

1. For the node stuff, I updated the failing test, and updated some node modules. Delete the node modules folder and re-install the node modules:

```
rm -rf node_modules
npm install
webpack
npm test
```

The tests in sbt should then work:

```
sbt
```

in SBT, run the following

```
; reload; clean; test
```

if the tests pass, then run the application

```
~run
```

Right now it is working on my machine. I'm running node version 6.3.0. After you have pulled in the changes from the repo and run the above commands, please let me know what the result is. Thanks.

**Comment by derfWayne** [comment]
What platform are you running on?

**Comment by shafiquejamal** [comment]
In production: Debian 8
In dev: Mac OS X 10.12.3 (Sierra)

**Comment by derfWayne** [comment]
**## Dev Platform is** 
System Version:	macOS 10.12.2 (16C68)
  Kernel Version:	Darwin 16.3.0
Do you think this may be having an affect on the errors I'm seeing.

I performed the above commands in SBT and in play activator. I've attached the spreadsheet of the results. 

Seems to be working in activator however SBT in IntelliJ is not cooperating. 

[launch_test.xlsx](https://github.com/shafiquejamal/play-authentication/files/798404/launch_test.xlsx)


I haven't actually run the application just yet. Test are taking a while.  Once I get that done I will let you know.

**Comment by derfWayne** [comment]
Results of activator test command:
[info] ScalaTest
[info] Run completed in 45 minutes, 37 seconds.
[info] Total number of tests run: 133
[info] Suites: completed 22, aborted 1
[info] Tests: succeeded 126, failed 7, canceled 0, ignored 0, pending 0
[info] *** 1 SUITE ABORTED ***
[info] *** 7 TESTS FAILED ***
[error] Error: Total 134, Failed 7, Errors 1, Passed 126
[error] Failed tests:
[error] 	access.registration.RegistrationControllerATest
[error] 	chat.ChatControllerATest
[error] 	user.ScalikeJDBCUserDAOUTest
[error] 	user.UserControllerATest
[error] Error during tests:
[error] 	access.authentication.AuthenticationControllerATest
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 2744 s, completed Feb 23, 2017 11:31:27 PM

**Comment by derfWayne** [comment]
After getting the test run in activator and running this command activator clean compile start, I was finally able to get the application stood up on my mac.
